insert into public.projects (slug, title, summary, description, status) values
('iremito-water-amboseli','Iremito Village Water Supply (Amboseli)','Community water access—phase 2 technical proposal','Phase 1 needs assessment complete; committee set up; local NGO engaged. Next: county endorsement, partnerships & fundraising, technical proposal, detailed planning, implementation, M&E.','in_progress'),
('amboseli-clean-cooking','Amboseli Clean Cooking','Feasibility & mechanisms evaluation for clean cooking solutions','Phase 1 site visit done; establishing partnerships; assess mechanisms; capacity building via site visits/webinars; then plan, implement, and evaluate.','planned'),
('lenkisem-sanitation','Lenkisem Secondary School – Sanitation','Dry sanitation/biogas options for school environments','Needs assessment complete; first draft technical proposal; mentorship event with partners completed. Next: site visits (dry sanitation & biogas), finalize proposal & fundraising, then planning/implementation/M&E.','in_progress'),
('manyatta-housing-innovation','Resilient Manyatta Housing Innovation (Amboseli)','Situational analysis of housing improvements and materials','Set up project team and coordinator; site visit and study current innovations; develop proposal, plan, implement, and evaluate.','planned'),
('school-mentorship-2025','Primary & Secondary School Mentorship (2025)','Concept development for STEM mentorship and hands-on activities','Define partners/schools, design activities, and fundraise; run hands-on sessions (e.g., solar oven, wind device, water system).','in_progress'),
('kumbi-irrigation-tana-river','Kumbi Village Irrigation (Tana River)','Irrigation system technical proposal with partners','Phase 1 site visit by partner completed; next: local NGO partners, second site visit, then planning/implementation/M&E.','in_progress'),
('dry-sanitation-pilot','Dry Sanitation Pilot (Amboseli)','Feasibility study for sanitation solutions','Set up team & coordinator; feasibility; proposal; planning; implementation; M&E.','planned'),
('meru-water-management','Meru Water Management Plan','Feasibility and planning for water management','Set up team & coordinator; feasibility; proposal; planning; implementation; M&E.','planned')
on conflict (slug) do update set title=excluded.title, summary=excluded.summary, description=excluded.description, status=excluded.status;
